# Generated by Django 3.0.4 on 2020-06-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emplyees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplyee_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_num', models.IntegerField()),
            ],
        ),
    ]
