# Generated by Django 3.0.4 on 2020-06-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emplyees',
            new_name='employees',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='emplyee_name',
            new_name='emplyoee_name',
        ),
    ]
