# Generated by Django 3.0.4 on 2020-06-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20200608_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_ID',
            field=models.IntegerField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
