# Generated by Django 3.0.4 on 2020-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_employees_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_ID',
            field=models.IntegerField(),
        ),
    ]
